# .readthedocs.yaml
# Read the Docs configuration file
# 版本必须是 2（RTD 新版标准）
version: 2

# 构建环境配置
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

# Sphinx 配置
sphinx:
  # 这里的路径是相对于仓库根目录的 Sphinx 配置文件位置
  configuration: docs/source/conf.py

# Python 依赖安装
python:
  install:
    - requirements: requirements.txt
